export const dinnerData = [
    {
      name: "Salmon With Grapefruit and Lentil Salad",
      img: "https://i.ibb.co/zH86qxF/dinner1.png",
      discription: "How we dream about our future",
      price: 11.69,
      details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
      id:"13",
      singleOne:"https://i.ibb.co/qsSq7br/d-1.png",
      singleTwo:"https://i.ibb.co/MPwq6jV/d-2.png",
      tax:1,
      deliveryFee:9.99,
      quantity:1,
      total:0
    },
    {
      name: "Lemony Salmon Piccata",
      img: "https://i.ibb.co/XtrGxVm/dinner2.png",
      discription: "How we dream about our future",
      price: 10.99,
      details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
      id:"14",
      singleOne:"https://i.ibb.co/WVMLMJY/s-3-2.jpg",
      singleTwo:"https://i.ibb.co/TcPYpnt/s-4.jpg",
      tax:1,
      deliveryFee:9.99,
      quantity:1,
      total:0
    },
    {
      name: "French fries with cheese",
      img: "https://i.ibb.co/mvZntRq/dinner3.png",
      discription: "How we dream about our future",
      details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
      price: 8.99,
      id:"15",
      singleOne:"https://i.ibb.co/1fG8Yzc/u-2.png",
      singleTwo:"https://i.ibb.co/GCtP32k/Capture.png",
      tax:1,
      deliveryFee:9.9,
      quantity:1,
      total:0
    },
    {
      name: "Gralic Butter Baked Salmon",
      img: "https://i.ibb.co/ZM88vSR/dinner4.png",
      discription: "How we dream about our future",
      details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
      price: 6.99,
      id:"16",
      singleOne:"https://i.ibb.co/PFYRzqx/v-1.jpg",
      singleTwo:"https://i.ibb.co/fqWdhrR/Capture.png",
      tax:1,
      deliveryFee:9.9,
      quantity:1,
      total:0
    },
    {
      name: "Park Tenderloin With Quiona Pilaf",
      img: "https://i.ibb.co/qJCPsXn/dinner.png",
      details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
      discription: "How we dream about our future",
      price: 12.99,
      id:"17",
      singleOne:"https://i.ibb.co/bQzwvVR/a-1.jpg",
      singleTwo:"https://i.ibb.co/qRt6MgQ/Capture.png",
      tax:1,
      deliveryFee:9.9,
      quantity:1,
      total:0
    },
    {
      name: "Baked Chicken",
      img: "https://i.ibb.co/DQTf6Zf/dinner-2.png",
      discription: "How we dream about our future",
      details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
      price: 9.99,
      id:"18",
      singleOne:"https://i.ibb.co/CWycztT/o-1.png",
      singleTwo:"https://i.ibb.co/PGm2YXw/o-2.png",
      tax:1,
      deliveryFee:9.9,
      quantity:1,
      total:0
    }
  ]