export const lunchData = [
    {
      img: "https://i.ibb.co/smtL405/lunch1.png" ,
      discription: "How we dream about our future",
      price: 23.99,
      name: "Healthy Meal plan",
      details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
      id:"7",
      singleOne:"https://i.ibb.co/0YJC4p2/l-2.png",
      singleTwo:"https://i.ibb.co/4WffG0g/Capture.png",
       tax:1,
      deliveryFee:9.99,
      quantity:1
    },
    {
      img: "https://i.ibb.co/jzxdJ3F/lunch2.png",
      discription: "How we dream about our future",
      price: 9.99,
      name: "Fried Chicken Bento",
      details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
      id:"8",
      singleOne:"https://i.ibb.co/XLbSyF6/Capture.png",
      singleTwo:"https://i.ibb.co/qJZRmyD/Capture-2.png",
       tax:1,
      deliveryFee:9.99,
      quantity:1
    },
    {
      img: "https://i.ibb.co/GWttSFm/lunch3.png",
      discription: "How we dream about our future",
      price: 8.99,
      name: "India Lunch",
      details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
      id:"9",
      singleOne:"https://i.ibb.co/t34Ps0h/i-1.png",
      singleTwo:"https://i.ibb.co/Z1rK6ys/i-2.png",
       tax:1,
      deliveryFee:9.99,
      quantity:1
    },
    {
      img: "https://i.ibb.co/MyHttMT/lunch5.png",
      discription: "How we dream about our future",
      price: 15.99,
      name: "Beef Steak",
      details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
      id:"10",
      singleOne:"https://i.ibb.co/L5gnjtC/Capture.png",
      singleTwo:"https://i.ibb.co/dW3bWbs/Capture.png",
       tax:1,
      deliveryFee:9.99,
      quantity:1
    },
    {
      img: "https://i.ibb.co/WcwZWVD/lunch-2.png",
      discription: "How we dream about our future",
      price: 7.99,
      name: "Hone-Soy-Glazed Salmon with Peppers",
      details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
      id:"11",
      singleOne:"https://i.ibb.co/GHB0mKt/f-1.jpg",
      singleTwo:"https://i.ibb.co/P4bktrn/Capture.png",
       tax:1,
      deliveryFee:9.99,
      quantity:1
    },
    {
      img: "https://i.ibb.co/QYYGXcb/lunch-1.png",
      discription: "How we dream about our future",
      price: 6.99,
      name: "Tarragon-Rubbed-Salmon",
      details: "Gay one the what walk then she. Demsene mention promise you justice arrived way. Amaizing foods are  or and increasing to in especially inquietude companions acceeptance admiration. Out weight it families distance wandered yet",
      id:"12",
      singleOne:"https://i.ibb.co/hZPyvvm/Capture.png",
      singleTwo:"https://i.ibb.co/12vXft7/s-1.png",
       tax:1,
      deliveryFee:9.99,
      quantity:1
    }
  ]